version: '3'

services:
  webapplication1:
    image: webapplication1
    ports:
      - "57471:80"
    build:
      context: .
      dockerfile: SadahamWeb/Dockerfile
    links:
      - db
    depends_on:
       - "db"
    networks:
      - mynetwork
    deploy:
      replicas: 2

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: overlay