version: '3'

services:
  webapp:
    image: dilhan2013/sadahamweb:latest
    ports:
      - "57471:80"
    depends_on:
       - "db"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: overlay
